### PR TITLE
Fixed links

### PR DESCRIPTION
**Pull request by Novaenn**

### CODE REVIEW

**Review by jacobtomlinson — CHANGES_REQUESTED** [review]
Thanks for raising this!

There is no `.` at the end of the domain (or any domain), that was just a problem with the issue formatting. Could you please remove it?

**Comment by Novaenn** [comment]
Oh, I'm sorry, I'll correct it.

**Comment by jacobtomlinson** [comment]
I'm afraid @danielacodes has successfully made this change. In future please be sure to check issues to see if someone has already grabbed it. And if you intend to work on it make sure you say so to avoid duplication.

I'm going to close this but it should still count towards your Hacktoberfest total. If you want to push the fixes I asked for as practice please go ahead. I'm also happy to send you opsdroid stickers for your contribution even though it didn't make it in.

We love to thank contributors by sending them [opsdroid stickers](https://medium.com/opsdroid/contributor-sticker-packs-738058ceda59)! Fill in the [claim form](https://forms.gle/iQZV9DjkaUiSaDXK6) to get yours!

**Comment by Novaenn** [comment]
Oh, thank you so much @jacobtomlinson! I will follow your tips next time.

**Pull request closed without merging**
