### PR TITLE
cleanup responsive view < 800px

### PR DESCRIPTION
**Pull request by hougasian**
Hope this helps. 
lmk if you need more.
#5

### CODE REVIEW

**Comment by hougasian** [comment]
screen shot 2017-10-04 at 7 20 50 am
screen shot 2017-10-04 at 7 20 58 am

**Comment by jacobtomlinson** [comment]
Awesome work!

This does look like it might be duplicating what #11 is trying to achieve. I'll compare them both when I get a chance and merge one or the other.

**Comment by hougasian** [comment]
no worries; this may be a cleaner approach, without inline style blocks.

**Comment by jacobtomlinson** [comment]
Sorry for the delay in checking this out! I've got some changes I'd like you to look at, but this is definitely awesome work! I'm afraid I'm away for a week now so I wont be able to check out changes until next weekend, but then I should be more responsive and back on top of things.

## Github banner
As raised in #11 the GitHub banner causes issues. See the iPad Pro example from Chrome Devtools. Could you look at getting it to not push the page out?

image

## Install instructions on mobile
When viewing on a small device like an iPhone 6S the code block has very large margins. Could you look at reducing them? It would also be nice to add some space between the code block and the chat animation.

image

## Text alignment on desktop
It looks like in your changes you've centred some text, but it needs to star left aligned on larger screens.

#### Yours
image

#### Live
image

**Comment by hougasian** [comment]
this commit should handle everything.
replaced ribbon with actual github version - it's not really a modern approach, but it works.
these are cool too: https://github.com/tholman/github-corners

**Comment by jacobtomlinson** [comment]
Sorry for the delay I've been on holiday. Thanks for making these changes!

I'll get this merged and also raise an issue to discuss replacing the banner with the github-corners. We can chat about it there.

**Comment by jacobtomlinson** [comment]
Ping me your address via DM on [Twitter](https://twitter.com/_jacobtomlinson) or [Gitter](https://gitter.im/opsdroid) and I'll post you some [opsdroid stickers](https://medium.com/opsdroid/stickers-for-contributors-a0a1f9c30ec1)!

**Pull request merged**
