### PR TITLE
feat: improvements

### PR DESCRIPTION
**Pull request by Yash-Singh1**
# Description

Improvements to the styling of the landing page. Adds syntax highlighting for the commands in the landing and adds links to the headers.

## Status
**READY**

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
Awesome thanks for this. Would you mind including before and after screenshots to make reviewing easier?

**Comment by Yash-Singh1** [comment]
This PR also removes the build files from the `css` folder and adds triple dashes to the top of the `main.scss` to make sure that builds: https://jekyllrb.com/docs/assets/.

**BEFORE**

Screenshot from 2022-07-19 09-33-27

**AFTER**

Screenshot from 2022-07-19 09-33-21

**BEFORE**

No links in features list

Selection_048

**AFTER**

Links in features list

Selection_047

**Comment by FabioRosado** [comment]
Happy with the link to the docs, but not sure about the code highlight, at least the colour doesn't seem a great fit for the overall theme

**Comment by Yash-Singh1** [comment]
> Happy with the link to the docs, but not sure about the code highlight, at least the colour doesn't seem a great fit for the overall theme

What color do you suggest? Or should I leave the code block alone?

**Comment by jacobtomlinson** [comment]
What about making the `$` a lighter version of the background blue so they stand out less. Then make the `pip` and `opsdroid` commands the green that the dollars are currently?

**Comment by Yash-Singh1** [comment]
@jacobtomlinson Just pushed 26f2a2d. Now looks like:

Screenshot from 2022-07-25 17-22-55

**Review by jacobtomlinson — APPROVED** [review]
LGTM many thanks

**Pull request merged**
