### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by subhajitsaha0x**
Added marquee tag for attraction.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Thanks for taking the time to raise this. I'm afraid the `<marquee>` element is obsolete and not supported in many browsers.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee

**Comment by subhajitsaha0x** [comment]
can you please some stickers? please

**Comment by jacobtomlinson** [comment]
I'm afraid we only send stickers for meaningful contributions. Here are some suggested ways you can contribute:

- Improve the documentation to help others get started
- Write skills, connectors or database modules
- Contribute to the opsdroid home page (it’s a Jekyll website)
- Post about your experience using opsdroid on your own blog
- Contribute to opsdroid audio (python voice client for opsdroid)
- Submit lots of useful issues (5–10 good ones is probably sticker worthy)
- Create logo variations and banners for promotion
- Contribute to opsdroid desktop (electron and react app)
- Promote opsdroid in a meaningful way

https://medium.com/opsdroid/stickers-for-contributors-a0a1f9c30ec1

**Comment by subhajitsaha0x** [comment]
i did contributed but you didnt like it.

**Pull request closed without merging**
