### PR TITLE
Redesign of the website

### PR DESCRIPTION
**Pull request by FabioRosado**
This is a rather extensive PR, the whole website was redesigned following the mockup that I created and was approved by the community.

I have changed a few things with this redesign:

- Removed bootstrap
- Updated font awesome CDN link
- Merged blog and modules javascript files into main
- Created an image folder and added the ones we use on the website

I wanted to create my own CSS file for two reasons: to try and learn a bit more about it and to avoid pulling the whole bootstrap rules into the site, the whole CSS file is about 15kb - if we minify it will go down to 12kb.

I have also moved the javascript into main.js and added the image folder to avoid having so many requests from the site making the site a bit faster.

I have also fixed issue #27 by changing the letter size and space available on the chat-demo window.

I've used CSS grid heavily and tested the site in both chrome, firefox, opera and safari - everything seems to be working okay (both in desktop and mobile view). One thing that I haven't fixed was the issue #21 and just hardcoded the parsers/matchers - at the moment this should be an okay approach since we haven't added any parsers in a while.

One thing that I am a bit unhappy with is the grey background in the middle of the page - it has been a pain to adjust it properly depending on different screen sizes - I tried to make it look okay-ish on all of them.

I am also just using one media query - min-width 920px because most of the layout looks just fine if we move all the grid boxes vertically on smaller screens.

I am not sure if we should just merge this redesign and get feedback from the community so I can fix any potential issues that might appear with other people using the site.

### CODE REVIEW

**Review by jacobtomlinson — CHANGES_REQUESTED** [review]
This is awesome! Thanks for doing this.

There are two issues I can see:
- There is a strange gap between the modules section and the footer
- The social icons are not displaying for me

Here's a screenshot of both issues
image

Once you're happy with it I'd be keen to get this merged.

(I'm using Firefox on MacOS)

**Comment by FabioRosado** [comment]
The gap was meant to be intentional as i will add that bit you asked me after the new layout is merged.

I’m unsure why the icons are not working since I’m using the font awesome cdn. I’ll try to figure out what the issue is. 

Is devtools complaining about something?

**Comment by jacobtomlinson** [comment]
Ah awesome! 

Can't see any issues in devtools. Are you able to reproduce it?

**Comment by FabioRosado** [comment]
I tested it on my Firefox browser as well but it was working as expected. I’m reading the troubleshooting guide on the FontAwesome wiki but nothing seems to apply to our case. No icons are being loaded (the download one isn’t either) so it’s not an afblocker thing and we are using the meta tag that they suggest we use. 

The cdn is the updated one from their site so I’m not sure. As a work around I could download those icons and serve them from the image folder that I created

—EDIT—
Perhaps adding `font-weight: 900` to the .fas css rule might fix the issue. I’m currently on the airport and won’t be able to change it until 9pm today.

Just as a test if you add that to the css rule will the icons appear?

**Comment by jacobtomlinson** [comment]
Looks like the whole fontawesome is just failing to load for me.

image

Perhaps it is worth looking for an alternative CDN or packaging the CSS in the project.

**Review by jacobtomlinson — APPROVED** [review]
Turns out it was my adblocker causing problems!

image

**Comment by FabioRosado** [comment]
Ah okay at least we figured out the reason why it was happening do you think we should just add the svg to the image folder to avoid this issue with other users?

**Comment by jacobtomlinson** [comment]
Nah I think it's fine this way. I have no idea why my adblocker was blocking it.

**Comment by FabioRosado** [comment]
Okay cool. The adblocker blocking the cnd is a thing as it was on the troubleshooting but it just mentioned social icons not all of them that’s why I didn’t pay it much attention haha

Thanks a lot for the time checking this up. I’ll merge it now :D

**Comment by jacobtomlinson** [comment]
No thank you for taking the time putting it together. Checking it is a least I can do!

**Pull request merged**
