### PR TITLE
New banner

### PR DESCRIPTION
**Pull request by felix-hack**
Implemented the black version of Git Corners, to get a feel of how it looks like (mentioned in #15). 
screenshot-2017-10-16 opsdroid an open source python chat-ops bot

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Nice work! Can you share a screenshot of the whole page? It looks like it may be a little small.

Also can you share a screenshot of the mobile view.

**Comment by felix-hack** [comment]
Of course! Here is a shot of the whole page:
screenshot-2017-10-16 opsdroid an open source python chat-ops bot
And here the mobile view:
bildschirmfoto vom 2017-10-16 um 16 14 32
It sadly crops a bit of the menu button as you've expected. We could give the whole header a bit more padding at the top, but this could also result in too much whitespace.

**Comment by jacobtomlinson** [comment]
Many thanks.

I agree adding whitespace is undesirable. Perhaps the banner should be hidden on mobile and a "fork me on github" option should be added to the menu (only on mobile). What do you think?

**Comment by felix-hack** [comment]
This may be the best way, because the old banner was also hidden on smaller devices. And there shouldn't be so much people forking repos on their phone.

**Comment by felix-hack** [comment]
Just did a small commit fixing it.

**Comment by jacobtomlinson** [comment]
Thanks!

**Comment by jacobtomlinson** [comment]
Ping me your address via DM on [Twitter](https://twitter.com/_jacobtomlinson) or [Gitter](https://gitter.im/opsdroid) and I'll post you some [opsdroid stickers](https://medium.com/opsdroid/stickers-for-contributors-a0a1f9c30ec1)!

**Pull request merged**
