### PR TITLE
documentation link updated to  https://docs.opsdroid.dev.

### PR DESCRIPTION
**Pull request by gauraviuiux**
documentation link has been updated

### CODE REVIEW

**Comment by gauraviuiux** [comment]
I have done this for hactober fest .I updated the links.I am a beginer here on github

**Comment by gauraviuiux** [comment]
I got the issue from issuehub.io

**Comment by jacobtomlinson** [comment]
Before I review this I just want to say thank you but Hacktoberfest hasn't started yet. If you want this contribution to count towards your total I suggest you close this and create a new PR tomorrow (after midnight October 1st).

**Comment by jacobtomlinson** [comment]
Closing as invalid as the issue has been resolved in another PR and @grvkmrpandit has been raising spam PRs in other parts of the project.

**Pull request closed without merging**
