### PR TITLE
buttons updated

### PR DESCRIPTION
**Pull request by devSouvik**
color of  'fork' and 'star' buttons are changed for better visibility

# Description

previously the buttons were almost invisible due to their colors. which has been fixed by changing them to black and the other one to the white 

## Status
**READY**

### CODE REVIEW

**Comment by FabioRosado** [comment]
Hello,

What do you mean the buttons are almost invisible? These buttons are the GitHub official ones and they are black text/icon on top of a white background. It's pretty difficult to make them better accessible than this 🤔

**Comment by jacobtomlinson** [comment]
@devSouvik please provide before and after screenshots to clarify what this change is doing.

**Comment by devSouvik** [comment]
before
previously they seemed to be like this :(
I tried changing their color to something like this
after

**Comment by FabioRosado** [comment]
opsdroid

This is how I got it. Perhaps you have some extension that is blocking the buttons to load? Like I said, this is the official one from github and they use javascript to load the styles.

Can you open your devtools and check what is shown in the console?

**Comment by devSouvik** [comment]
ok, I got it..my bad, thank you :)

**Pull request closed without merging**
