### PR TITLE
404 Error image not loding for long URLs.

### PR DESCRIPTION
**Pull request by Om-Raj**
The **relative file path is updated** so that it can **load 404 error** image even if the wrong URL extends **more than two** sub-directories.

### CODE REVIEW

**Review by jacobtomlinson — CHANGES_REQUESTED** [review]
Thanks for raising this! I think it would be better to switch to an absolute url instead. 

``

**Comment by Om-Raj** [comment]
I hope I've fixed the issue properly this time.

**Comment by FabioRosado** [comment]
Thanks for working on this @Om-Raj, the reason why I left the src like that was because we don't really have any subfolders other than the index one. But this is probably best practice and should be fixed in case we decided to expand the site further 👍

**Comment by Om-Raj** [comment]
So is my pull request accepted...

**Comment by jacobtomlinson** [comment]
Sorry but can you please change it to my suggestion of a truncated absolute url. I would rather not have the domain in the url as we may change that eventually.

**Comment by Om-Raj** [comment]
I would suerly revert back the change if you want me to.

**Comment by jacobtomlinson** [comment]
Please change it to this `/images/404.svg`.

**Comment by jacobtomlinson** [comment]
🎉

**Review by jacobtomlinson — APPROVED** [review]

**Comment by jacobtomlinson** [comment]
Ping me your address via DM on [Twitter](https://twitter.com/_jacobtomlinson) or [Gitter](https://gitter.im/opsdroid) and I'll post you some [opsdroid stickers](https://medium.com/opsdroid/stickers-for-contributors-a0a1f9c30ec1)!

**Pull request merged**
