### PR TITLE
Use YouTube FA icon

### PR DESCRIPTION
**Pull request by lex111**
:muscle:

### CODE REVIEW

**Comment by lex111** [comment]
@FabioRosado the width remains the same, it's the YT channel, so there must be an *appropriate* icon, isn’t it? Strange now.

**Comment by lex111** [comment]
| Before   | After    |
| -------- | -------- |
| image | image |

On the contrary, it’s ugly now, the icon is knocked out of the general row, due to the large empty space on the sides!

**Comment by FabioRosado** [comment]
That is the main reason why I choose the caret instead of the youtube icon - the youtube icon is wider than the rest of the icons and that doesn't look good. 

Also, notice that the youtube icon is nothing more than a left caret so I think using just this icon still makes it obvious that this icon will link to youtube right?

**Comment by lex111** [comment]
You are a perfectionist :(
For me there is no difference, but I see a recognizable logo.

**Comment by lex111** [comment]
The difference is 3 px.. fine, then let's reduce the padding for YT icon, do we?

**Comment by lex111** [comment]
... but this is also not an option, because it will be noticeable (?) that padding is different :(

**Comment by jacobtomlinson** [comment]
I actually agree with @lex111 in this case, sorry @FabioRosado! The YouTube icon is a left caret inside a rounded box, I think using the official icon is more recognisable than the caret on its own. 

I agree the extra width is a shame but I think it is worth it here.

One other solution would be to make the icon smaller, perhaps someone could put in another PR for that.

**Pull request merged**
