### PR TITLE
Add Latest Posts section to site

### PR DESCRIPTION
**Pull request by pjbollinger**
This should resolve isssue #6.

Following is a screenshot of what it looks like.

screen shot 2017-10-08 at 9 54 06 am

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Many thanks for this! Apologies in the delay for reviewing this, I've been on holiday.

This is exactly the functionality I was looking for in #6. However I'm not 100% sure on the layout. I'll list some questions below, I would be really interested in your thoughts rather than you just implementing exactly what I say as I may not be right :smile:.

- You've put the latest posts section next to the word-clouds of modules. This is slightly mixing two different types of content in a similar looking way. Perhaps it would be better to have a whole separate section, either blow the modules or above them. This way each post could be bigger and include an excerpt and perhaps a hero image if there is one in the feed.
- You've numbered the posts from 1 to 3, what information are you trying to convey here? The date already implies the order of publication.
- In the strap line you've said "on its blog", however this is the opsdroid website so perhaps "our blog" or "the blog" may be more appropriate.
- I'm not sure I like the date in green. I appreciate you've used the `$brand-green` variable in the css which is a nice touch, however I'm not sure I like how it looks. Perhaps a light grey would be better.
- Also with the article titles I'm not sure on the colour.

**Comment by pjbollinger** [comment]
No problem, I hope you had a good holiday.

* I thought about adding them above or below but worried that it would take away from the content by being full width. That’s why I opted for being off to the side, so people could a little news update without the site becoming a blog and brand page mixed.
* I agree the wording should change to “the blog”
* The numeric labels was meant to give the posts some weight. I don’t think removing the blocks would be good but maybe removing the numbers and treat it like a bullet list. Thoughts? I don’t think removing the blocks and making text bigger would be good because it would make it messy.
* Aw, the green text didn’t grow on you. ;) I’ll probably change it to the same grey as the headers above.
* I chose blue because most links on the page are blue in that area of the page.

Just wanted give my thoughts.

**Comment by jacobtomlinson** [comment]
- I know what you mean. I wonder whether it would go well as a half width item next to something else, either another piece of content or just a bit of branding.
- Great
- Yes I totally agree, the blocks give weight but I think you should drop the numbers (and maybe reduce the size a little). Also what would the blog section look like to the left of the modules instead of the right?
- Cool
- Ok fair enough.

**Comment by jacobtomlinson** [comment]
What are your thoughts? Are you happy to make the changes we discussed and then I'll get it merged?

**Comment by pjbollinger** [comment]
Hello, I looked at moving the blog and those "bullets" beside the blog post. Fixed up the wording and coloring of the date. What do you think of the attached screenshot?
screen shot 2017-10-18 at 7 03 18 am

EDIT: ~~If it looks good, I'll commit.~~ I have to go to work, so I committed the changes, feel free to merge if it looks good to you. If you're not crazy with having the blog down in the lower section, can you think of something else to help balance it in its own level on the page?

**Comment by jacobtomlinson** [comment]
This is great! I'll merge this. We can always move it somewhere else at a later date as more content is added to the site.

**Pull request merged**
