### PR TITLE
Updating main.css

### PR DESCRIPTION
**Pull request by Anugya-Gogoi**
Changing the background color from a single color to gradient

### CODE REVIEW

**Review by FabioRosado — CHANGES_REQUESTED** [review]
Hello,
I appreciate you raising this PR and contributing to the website.

Out of curiosity, why do you think this particular gradient will improve the website?

Also, the file `main.css` was minified and I would like to keep the scss file updated so you will have to update that file as well.

Thank you

**Comment by Anugya-Gogoi** [comment]
I think that this gradient makes the website look very elegant.
Also, I'll be sure to update the file. Thanks.

**Comment by FabioRosado** [comment]
I understand, but I'm not sure if the light pink will improve the site since it looks like outside the color scheme 🤔

**Comment by Anugya-Gogoi** [comment]
The color is a mixture of pale purple and grey😊

**Comment by Anugya-Gogoi** [comment]
I hope the changes do not affect the overall appearance of the website. The gradient deviates only slightly from the almost white color of the site and it will, I believe, add some amount of "fun" factor to the website

**Pull request closed without merging**
